-- ==========================================
-- 1. LIMPIEZA DE ESQUEMA (Opcional)
-- ==========================================
/*
DROP TABLE SOLICITUD CASCADE CONSTRAINTS;
DROP TABLE COMPONENTE CASCADE CONSTRAINTS;
DROP TABLE OFERTA CASCADE CONSTRAINTS;
DROP TABLE PROGRAMA CASCADE CONSTRAINTS;
DROP TABLE SEDE CASCADE CONSTRAINTS;
DROP TABLE UNIVERSIDAD CASCADE CONSTRAINTS;
DROP TABLE POSTULANTE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_POSTULANTE;
DROP SEQUENCE SEQ_UNIVERSIDAD;
DROP SEQUENCE SEQ_SEDE;
DROP SEQUENCE SEQ_PROGRAMA;
DROP SEQUENCE SEQ_OFERTA;
DROP SEQUENCE SEQ_SOLICITUD;
DROP SEQUENCE SEQ_COMPONENTE;
*/

-- ==========================================
-- 2. CREACIÓN DE SECUENCIAS
-- ==========================================
CREATE SEQUENCE SEQ_POSTULANTE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_UNIVERSIDAD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SEDE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROGRAMA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_OFERTA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOLICITUD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_COMPONENTE START WITH 1 INCREMENT BY 1;

-- ==========================================
-- 3. CREACIÓN DE TABLAS
-- ==========================================

CREATE TABLE POSTULANTE (
    id NUMBER DEFAULT SEQ_POSTULANTE.NEXTVAL PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    telefono VARCHAR2(20),
    direccion VARCHAR2(200),
    fecha_nac DATE NOT NULL,
    usuario VARCHAR2(50) UNIQUE NOT NULL,
    clave VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'POSTULANTE' CHECK (rol IN ('ADMIN', 'POSTULANTE'))
);

CREATE TABLE UNIVERSIDAD (
    id NUMBER DEFAULT SEQ_UNIVERSIDAD.NEXTVAL PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    pais VARCHAR2(50) NOT NULL,
    ciudad VARCHAR2(100) NOT NULL,
    direccion VARCHAR2(200),
    telefono VARCHAR2(20)
);

CREATE TABLE SEDE (
    id NUMBER DEFAULT SEQ_SEDE.NEXTVAL PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    direccion VARCHAR2(200),
    id_universidad NUMBER NOT NULL,
    CONSTRAINT fk_sede_univ FOREIGN KEY (id_universidad) REFERENCES UNIVERSIDAD(id)
);

CREATE TABLE PROGRAMA (
    id NUMBER DEFAULT SEQ_PROGRAMA.NEXTVAL PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    descripcion VARCHAR2(500),
    area VARCHAR2(50) CHECK (area IN ('Especialidad', 'Maestría', 'Doctorado')),
    tipo_financiamiento VARCHAR2(50)
);

CREATE TABLE OFERTA (
    id NUMBER DEFAULT SEQ_OFERTA.NEXTVAL PRIMARY KEY,
    id_programa NUMBER NOT NULL,
    id_sede NUMBER NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    cupos_disponibles NUMBER CHECK (cupos_disponibles >= 0),
    estado VARCHAR2(20) DEFAULT 'Activa' CHECK (estado IN ('Activa', 'Cerrada')),
    CONSTRAINT fk_oferta_prog FOREIGN KEY (id_programa) REFERENCES PROGRAMA(id),
    CONSTRAINT fk_oferta_sede FOREIGN KEY (id_sede) REFERENCES SEDE(id)
);

CREATE TABLE SOLICITUD (
    id NUMBER DEFAULT SEQ_SOLICITUD.NEXTVAL PRIMARY KEY,
    id_postulante NUMBER NOT NULL,
    id_oferta NUMBER NOT NULL,
    fecha_postulacion DATE DEFAULT SYSDATE,
    resumen_interes CLOB NOT NULL,
    estado VARCHAR2(20) DEFAULT 'Pendiente' CHECK (estado IN ('Pendiente', 'Aceptada', 'Rechazada')),
    CONSTRAINT fk_solicitud_post FOREIGN KEY (id_postulante) REFERENCES POSTULANTE(id),
    CONSTRAINT fk_solicitud_ofe FOREIGN KEY (id_oferta) REFERENCES OFERTA(id),
    CONSTRAINT uq_postulante_oferta UNIQUE (id_postulante, id_oferta) -- Para probar DUP_VAL_ON_INDEX
);

CREATE TABLE COMPONENTE (
    id NUMBER DEFAULT SEQ_COMPONENTE.NEXTVAL PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    id_programa NUMBER NOT NULL,
    CONSTRAINT fk_comp_prog FOREIGN KEY (id_programa) REFERENCES PROGRAMA(id)
);
